package tn.cni.injez.model;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum Pays {
@JsonProperty("أفغانستان")
أفغانستان,
@JsonProperty("ألبانيا")
ألبانيا,
@JsonProperty("الجزائر")
الجزائر,
@JsonProperty("أندورا")
أندورا,
@JsonProperty("أنغولا")
أنغولا,
@JsonProperty("الأرجنتين")
الأرجنتين,
@JsonProperty("أرمينيا")
أرمينيا,
@JsonProperty("أستراليا")
أستراليا,
@JsonProperty("النمسا")
النمسا,
@JsonProperty("أذربيجان")
أذربيجان,
@JsonProperty("البحرين")
البحرين,
@JsonProperty("بنغلاديش")
بنغلاديش,
@JsonProperty("بيلاروسيا")
بيلاروسيا,
@JsonProperty("بلجيكا")
بلجيكا,
@JsonProperty("بوليفيا")
بوليفيا,
@JsonProperty("بوتسوانا")
بوتسوانا,
@JsonProperty("البرازيل")
البرازيل,
@JsonProperty("بروناي")
بروناي,
@JsonProperty("بلغاريا")
بلغاريا,
@JsonProperty("بوروندي")
بوروندي,
@JsonProperty("كمبوديا")
كمبوديا,
@JsonProperty("الكاميرون")
الكاميرون,
@JsonProperty("كندا")
كندا,
@JsonProperty("تشاد")
تشاد,
@JsonProperty("تشيلي")
تشيلي,
@JsonProperty("الصين")
الصين,
@JsonProperty("كولومبيا")
كولومبيا,
@JsonProperty("الكونغو")
الكونغو,
@JsonProperty("كوستاريكا")
كوستاريكا,
@JsonProperty("كرواتيا")
كرواتيا,
@JsonProperty("كوبا")
كوبا,
@JsonProperty("قبرص")
قبرص,
@JsonProperty("التشيك")
التشيك,
@JsonProperty("الدنمارك")
الدنمارك,
@JsonProperty("جيبوتي")
جيبوتي,
@JsonProperty("إكوادور")
إكوادور,
@JsonProperty("مصر")
مصر,
@JsonProperty("السلفادور")
السلفادور,
@JsonProperty("إريتريا")
إريتريا,
@JsonProperty("إستونيا")
إستونيا,
@JsonProperty("إثيوبيا")
إثيوبيا,
@JsonProperty("فنلندا")
فنلندا,
@JsonProperty("فرنسا")
فرنسا,
@JsonProperty("غامبيا")
غامبيا,
@JsonProperty("جورجيا")
جورجيا,
@JsonProperty("ألمانيا")
ألمانيا,
@JsonProperty("غانا")
غانا,
@JsonProperty("اليونان")
اليونان,
@JsonProperty("غينيا")
غينيا,
@JsonProperty("هايتي")
هايتي,
@JsonProperty("هندوراس")
هندوراس,
@JsonProperty("المجر")
المجر,
@JsonProperty("أيسلندا")
أيسلندا,
@JsonProperty("الهند")
الهند,
@JsonProperty("إندونيسيا")
إندونيسيا,
@JsonProperty("إيران")
إيران,
@JsonProperty("العراق")
العراق, 
@JsonProperty("إيطاليا")
إيطاليا,
@JsonProperty("جامايكا")
جامايكا,
@JsonProperty("اليابان")
اليابان,
@JsonProperty("الأردن")
الأردن,
@JsonProperty("كازاخستان")
كازاخستان,
@JsonProperty("كينيا")
كينيا,
@JsonProperty("كوريا الجنوبية")
كوريا_الجنوبية,
@JsonProperty("كوسوفو")
كوسوفو,
@JsonProperty("الكويت")
الكويت,
@JsonProperty("لاتفيا")
لاتفيا,
@JsonProperty("لبنان")
لبنان,
@JsonProperty("ليبيا")
ليبيا,
@JsonProperty("ليتوانيا")
ليتوانيا,
@JsonProperty("لوكسمبورغ")
لوكسمبورغ,
@JsonProperty("مقدونيا")
مقدونيا,
@JsonProperty("مدغشقر")
مدغشقر,
@JsonProperty("ماليزيا")
ماليزيا,
@JsonProperty("مالي")
مالي,
@JsonProperty("مالطا")
مالطا,
@JsonProperty("موريتانيا")
موريتانيا,
@JsonProperty("المكسيك")
المكسيك,
@JsonProperty("موناكو")
موناكو,
@JsonProperty("منغوليا")
منغوليا,
@JsonProperty("المغرب")
المغرب,
@JsonProperty("موزمبيق")
موزمبيق,
@JsonProperty("ميانمار")
ميانمار,
@JsonProperty("ناميبيا")
ناميبيا,
@JsonProperty("نيبال")
نيبال,
@JsonProperty("هولندا")
هولندا,
@JsonProperty("نيوزيلندا")
نيوزيلندا,
@JsonProperty("نيجيريا")
نيجيريا,
@JsonProperty("النرويج")
النرويج,
@JsonProperty("عمان")
عمان,
@JsonProperty("باكستان")
باكستان,
@JsonProperty("بنما")
بنما,
@JsonProperty("باراغواي")
باراغواي,
@JsonProperty("بيرو")
بيرو,
@JsonProperty("الفلبين")
الفلبين,
@JsonProperty("بولندا")
بولندا,
@JsonProperty("البرتغال")
البرتغال,
@JsonProperty("قطر")
قطر,
@JsonProperty("رومانيا")
رومانيا,
@JsonProperty("روسيا")
روسيا,
@JsonProperty("فلسطين")
فلسطين,
@JsonProperty("رواندا")
رواندا,
@JsonProperty("السعودية")
السعودية,
@JsonProperty("السنغال")
السنغال,
@JsonProperty("صربيا")
صربيا,
@JsonProperty("سيشيل")
سيشيل,
@JsonProperty("سيراليون")
سيراليون,
@JsonProperty("سنغافورة")
سنغافورة,
@JsonProperty("سلوفاكيا")
سلوفاكيا,
@JsonProperty("سلوفينيا")
سلوفينيا,
@JsonProperty("الصومال")
الصومال,
@JsonProperty("جنوب إفريقيا")
جنوب_إفريقيا,
@JsonProperty("إسبانيا")
إسبانيا,
@JsonProperty("سريلانكا")
سريلانكا,
@JsonProperty("السودان")
السودان,
@JsonProperty("سوازيلاند")
سوازيلاند,
@JsonProperty("السويد")
السويد,
@JsonProperty("سويسرا")
سويسرا,
@JsonProperty("سوريا")
سوريا,
@JsonProperty("تايوان")
تايوان,
@JsonProperty("طاجيكستان")
طاجيكستان,
@JsonProperty("تنزانيا")
تنزانيا,
@JsonProperty("تايلاند")
تايلاند,
@JsonProperty("توغو")
توغو,
@JsonProperty("تونس")
تونس,
@JsonProperty("تركيا")
تركيا,
@JsonProperty("تركمانستان")
تركمانستان,
@JsonProperty("أوغندا")
أوغندا,
@JsonProperty("أوكرانيا")
أوكرانيا,
@JsonProperty("الإمارات")
الإمارات,
@JsonProperty("بريطانيا")
بريطانيا,
@JsonProperty("الولايات المتحدة الأمريكية")
الولايات_المتحدة_الأمريكية,
@JsonProperty("أوروغواي")
أوروغواي,
@JsonProperty("أوزبكستان")
أوزبكستان,
@JsonProperty("فنزويلا")
فنزويلا,
@JsonProperty("فيتنام")
فيتنام,
@JsonProperty("اليمن")
اليمن

 
}
