export enum EnumGouvernorat {
    ARIANA="أريانة",
	BEJA="باجة",
	BENAROUS="بن عروس",
	BIZERTE="بنزرت",
	GABES="قابس",
	GAFSA="قفصة",
	JENDOUBA="جندوبة",
	KAIROUAN="القيروان",
	KASSERINE="القصرين",
	KEBILI="قبلي",
	KEF="الكاف",
	MAHDIA="المهدية",
	MANOUBA="منوبة",
	MEDENINE="مدنين",
	MONASTIR="المنستير",
	NABEUL="نابل",
	SFAX="صفاقس",
	SIDIBOUZID="سيدي بوزيد",
	SILIANA="سليانة",
	SOUSSE="سوسة",
	TATAOUINE="تطاوين",
	TOZEUR="توزر",
	TUNIS="تونس",
	ZAGHOUAN="زغوان"
}